version: "1"

networks:
  sig-network:
    driver: bridge
services:
  quasar:
    tty: true # docker run -t
    restart: unless-stopped
    image: quasar
    build:
      dockerfile: ./Dockerfile
      context: ./
      target: develop-stage
    ports:
      - "8080:8080"
      - "4000:4000"
      - "6006:6006"
    volumes:
      - "./:/app"
    # env_file:
    #   - .env.local
